<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rental Code {{ $rentalCode->rental_code }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background: white;
        }
        
        .document-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: white;
        }
        
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 10px 10px 0 0;
            margin-bottom: 0;
        }
        
        .header h1 {
            font-size: 28px;
            font-weight: 300;
            margin-bottom: 10px;
        }
        
        .header p {
            opacity: 0.9;
            font-size: 16px;
        }
        
        .code-highlight {
            background: white;
            color: #667eea;
            padding: 20px;
            border-radius: 8px;
            font-family: monospace;
            font-size: 32px;
            font-weight: bold;
            text-align: center;
            margin: 20px 0;
            border: 3px solid #667eea;
        }
        
        .content {
            background: #f8f9fa;
            padding: 40px;
            border-radius: 0 0 10px 10px;
        }
        
        .section {
            margin-bottom: 30px;
            background: white;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #667eea;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        
        .section h3 {
            color: #667eea;
            margin: 0 0 20px 0;
            font-size: 18px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
        }
        
        .info-item {
            margin-bottom: 15px;
            padding: 12px;
            background: #f8f9fa;
            border-radius: 5px;
            border: 1px solid #e9ecef;
        }
        
        .label {
            font-weight: 600;
            color: #495057;
            display: block;
            margin-bottom: 5px;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .value {
            color: #212529;
            font-size: 14px;
            font-weight: 500;
        }
        
        .footer {
            margin-top: 30px;
            text-align: center;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 8px;
            color: #6c757d;
            font-size: 12px;
            border-top: 1px solid #e9ecef;
        }
        
        @media print {
            .document-container {
                margin: 0;
                padding: 0;
            }
            .header {
                border-radius: 0;
            }
            .content {
                border-radius: 0;
            }
        }
    </style>
</head>
<body>
    <div class="document-container">
        <div class="header">
            <h1>🏠 Rental Code Generated</h1>
            <p>Generated by: <strong>{{ $agentName }}</strong></p>
            <div class="code-highlight">{{ $rentalCode->rental_code }}</div>
        </div>
        
        <div class="content">
            <div class="section">
                <h3>📋 Rental Details</h3>
                <div class="info-grid">
                    <div class="info-item">
                        <span class="label">Rental Code</span>
                        <span class="value">{{ $rentalCode->rental_code }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Date</span>
                        <span class="value">{{ $rentalCode->rental_date ? $rentalCode->rental_date->format('d/m/Y') : 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Consultation Fee</span>
                        <span class="value">£{{ number_format($rentalCode->consultation_fee, 2) }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Payment Method</span>
                        <span class="value">{{ $rentalCode->payment_method ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Property</span>
                        <span class="value">{{ $rentalCode->property ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Licensor</span>
                        <span class="value">{{ $rentalCode->licensor ?? 'N/A' }}</span>
                    </div>
                </div>
            </div>

            @if($client)
            <div class="section">
                <h3>👤 Client Information</h3>
                <div class="info-grid">
                    <div class="info-item">
                        <span class="label">Full Name</span>
                        <span class="value">{{ $client->full_name ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Date of Birth</span>
                        <span class="value">{{ $client->date_of_birth ? $client->date_of_birth->format('jS F Y') : 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Phone Number</span>
                        <span class="value">{{ $client->phone_number ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Email</span>
                        <span class="value">{{ $client->email ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Nationality</span>
                        <span class="value">{{ $client->nationality ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Current Address</span>
                        <span class="value">{{ $client->current_address ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Company/University</span>
                        <span class="value">{{ $client->company_university_name ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Position/Role</span>
                        <span class="value">{{ $client->position_role ?? 'N/A' }}</span>
                    </div>
                </div>
            </div>
            @endif

            <div class="section">
                <h3>👨‍💼 Agent Information</h3>
                <div class="info-grid">
                    <div class="info-item">
                        <span class="label">Client Code</span>
                        <span class="value">{{ $rentalCode->rent_by_agent ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Created</span>
                        <span class="value">{{ $rentalCode->created_at ? $rentalCode->created_at->format('d/m/Y H:i') : 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Last Updated</span>
                        <span class="value">{{ $rentalCode->updated_at ? $rentalCode->updated_at->format('d/m/Y H:i') : 'N/A' }}</span>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="footer">
            <p>This document was generated automatically by the Truehold Group System.</p>
            <p>Generated on: {{ now()->format('d/m/Y H:i:s') }}</p>
        </div>
    </div>
</body>
</html>