<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Invoice Generated</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: #2c2c2c;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
        }
        .content {
            background: #f9f9f9;
            padding: 20px;
            border-radius: 0 0 8px 8px;
        }
        .invoice-details {
            background: white;
            padding: 15px;
            border-radius: 8px;
            margin: 15px 0;
            border-left: 4px solid #2c2c2c;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            color: #666;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>New Invoice Generated</h1>
        <p>Invoice #{{ $invoice->invoice_number }}</p>
    </div>
    
    <div class="content">
        <p>Hello,</p>
        
        <p>A new invoice has been generated by <strong>{{ $agentName }}</strong> and requires your attention.</p>
        
        <div class="invoice-details">
            <h3>Invoice Details:</h3>
            <p><strong>Invoice Number:</strong> {{ $invoice->invoice_number }}</p>
            <p><strong>Client:</strong> {{ $invoice->client_name }}</p>
            <p><strong>Amount:</strong> £{{ number_format($invoice->total_amount, 2) }}</p>
            <p><strong>Due Date:</strong> {{ $invoice->due_date->format('M d, Y') }}</p>
            <p><strong>Generated by:</strong> {{ $agentName }}</p>
            <p><strong>Date Generated:</strong> {{ $invoice->created_at->format('M d, Y \a\t g:i A') }}</p>
        </div>
        
        <p>The invoice PDF is attached to this email for your review.</p>
        
        <p>Please review the invoice and take any necessary action.</p>
        
        <p>Best regards,<br>
        Truehold Group System</p>
    </div>
    
    <div class="footer">
        <p>This is an automated notification from the Truehold Group invoice system.</p>
    </div>
</body>
</html>
