<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Rental Code Generated</title>
    <style>
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            line-height: 1.6; 
            color: #333; 
            margin: 0; 
            padding: 0; 
            background-color: #f5f5f5;
        }
        .container { 
            max-width: 800px; 
            margin: 20px auto; 
            background: white; 
            border-radius: 10px; 
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header { 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
            color: white; 
            padding: 30px; 
            text-align: center; 
        }
        .header h1 { 
            margin: 0; 
            font-size: 28px; 
            font-weight: 300;
        }
        .header p { 
            margin: 10px 0 0 0; 
            opacity: 0.9; 
            font-size: 16px;
        }
        .content { 
            padding: 40px; 
        }
        .section { 
            margin-bottom: 30px; 
            border-left: 4px solid #667eea; 
            padding-left: 20px;
        }
        .section h3 { 
            color: #667eea; 
            margin: 0 0 20px 0; 
            font-size: 20px; 
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .info-grid { 
            display: grid; 
            grid-template-columns: 1fr 1fr; 
            gap: 15px; 
        }
        .info-item { 
            margin-bottom: 15px; 
            padding: 10px; 
            background: #f8f9fa; 
            border-radius: 5px;
            border: 1px solid #e9ecef;
        }
        .label { 
            font-weight: 600; 
            color: #495057; 
            display: block; 
            margin-bottom: 5px;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .value { 
            color: #212529; 
            font-size: 16px;
            font-weight: 500;
        }
        .footer { 
            background: #f8f9fa; 
            padding: 20px; 
            text-align: center; 
            font-size: 12px; 
            color: #6c757d; 
            border-top: 1px solid #e9ecef;
        }
        .highlight {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            text-align: center;
        }
        .highlight h2 {
            margin: 0;
            font-size: 24px;
            font-weight: 300;
        }
        @media (max-width: 600px) {
            .info-grid { 
                grid-template-columns: 1fr; 
            }
            .container {
                margin: 10px;
            }
            .content {
                padding: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🏠 New Rental Code Generated</h1>
            <p>Generated by: <strong>{{ $agentName }}</strong></p>
        </div>

        <div class="content">
            <div class="highlight">
                <h2>Rental Code: {{ $rentalCode->rental_code }}</h2>
            </div>

            <div class="section">
                <h3>📋 Rental Details</h3>
                <div class="info-grid">
                    <div class="info-item">
                        <span class="label">Rental Code</span>
                        <span class="value">{{ $rentalCode->rental_code }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Rental Date</span>
                        <span class="value">{{ $rentalCode->rental_date ? $rentalCode->rental_date->format('d/m/Y') : 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Consultation Fee</span>
                        <span class="value">£{{ number_format($rentalCode->consultation_fee, 2) }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Payment Method</span>
                        <span class="value">
                            @php
                                $paymentMethod = $rentalCode->payment_method ?? 'N/A';
                                $emoji = '';
                                if (strtolower($paymentMethod) === 'transfer' || strtolower($paymentMethod) === 'card machine') {
                                    $emoji = '⚡';
                                } elseif (strtolower($paymentMethod) === 'cash') {
                                    $emoji = '💰';
                                }
                            @endphp
                            @if($emoji)
                                {{ $emoji }} 
                            @endif
                            {{ $paymentMethod }}
                        </span>
                    </div>
                    <div class="info-item">
                        <span class="label">Property</span>
                        <span class="value">{{ $rentalCode->property ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Licensor</span>
                        <span class="value">{{ $rentalCode->licensor ?? 'N/A' }}</span>
                    </div>
                </div>
            </div>

            <div class="section">
                <h3>👤 Client Information</h3>
                <div class="info-grid">
                    <div class="info-item">
                        <span class="label">Full Name</span>
                        <span class="value">{{ $client->full_name ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Date of Birth</span>
                        <span class="value">{{ $client->date_of_birth ? $client->date_of_birth->format('jS F Y') : 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Phone Number</span>
                        <span class="value">{{ $client->phone_number ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Email</span>
                        <span class="value">{{ $client->email ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Nationality</span>
                        <span class="value">{{ $client->nationality ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Current Address</span>
                        <span class="value">{{ $client->current_address ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Company/University</span>
                        <span class="value">{{ $client->company_university_name ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Position/Role</span>
                        <span class="value">{{ $client->position_role ?? 'N/A' }}</span>
                    </div>
                </div>
            </div>

            <div class="section">
                <h3>👨‍💼 Agent Information</h3>
                <div class="info-grid">
                    <div class="info-item">
                        <span class="label">Rent By Agent</span>
                        <span class="value">{{ $rentalCode->rent_by_agent ?? 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Created</span>
                        <span class="value">{{ $rentalCode->created_at ? $rentalCode->created_at->format('d/m/Y H:i') : 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <span class="label">Last Updated</span>
                        <span class="value">{{ $rentalCode->updated_at ? $rentalCode->updated_at->format('d/m/Y H:i') : 'N/A' }}</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer">
            <p>This email was automatically generated by the Truehold Group System.</p>
            <p>Generated on: {{ now()->format('d/m/Y H:i:s') }}</p>
        </div>
    </div>
</body>
</html>